name: Build and Export Next.js Static Site

on:
  push:
    branches: [main] # or your branch

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: prototype

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build and export
        run: npm run build

      - name: Upload exported site
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: out
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./prototype/out


